name: Deploy Laravel

on:
  push:
    branches:
      - master
      - dev # jalankan hanya jika push ke branch master (production)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, bcmath, intl, pdo_mysql
          tools: composer:v2

      - name: Install dependencies (production only)
        run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist

      - name: Run Laravel build commands
        run: |
          cp .env.example .env || true
          php artisan key:generate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # === Deploy ke server via SSH ===
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/laravel-app   # sesuaikan path project di server
            git pull origin master
            composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
